destination: _site

title: Musing of Kurt Wolf
email: itguy614@gmail.com
description: >-
  Musings of Kurt Wolf, a collection of thoughts, ideas, and reflections on
  various topics including technology, life, and personal experiences.
baseurl: ""
url: "http://wolfienet.com"

author: Kurt Wolf

theme: bulma-clean-theme
fixed_navbar: top

plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-feed
    - jekyll-seo-tag
    - kramdown-parser-gfm
    - jekyll-redirect-from

exclude:
    - Gemfile
    - clean-theme.gemspec
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/

permalink: /:year/:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num"

livereload: true
